server:
  port: 8088
  max-http-header-size: 80KB
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
#    password: Wy_123456
    hikari:
      connection-timeout: 30000  # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认30秒
      minimum-idle: 5  # 最小连接数
      maximum-pool-size: 20  # 最大连接数
      auto-commit: true  # 自动提交
      idle-timeout: 600000  # 连接超时的最大时长（毫秒），超时则被释放（retired），默认10分钟
      pool-name: DateSourceHikariCP  # 连接池的名字
      max-lifetime: 1800000  # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 51200  # 文件上传大小限制为500kb
      max-request-size: 51200  # 请求大小限制为500KB
  profiles:
    active: dev  # 设置环境为生产环境

mybatis:
  type-aliases-package: com.imooc.pojo  # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/**/*.xml  # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  #  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的时候, 判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

payment:
  imooc-user-id: 7733279-1950746552
  password: 3209-ir02-ir0k-r90o
